name: Deployment
on:
  push:
    branches:
      - main
    paths-ignore: 
      - ./github

concurrency: production

jobs:
  test-build-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          yarn install
      - name: Build application
        run: |
          yarn build
  deploy:
    runs-on: ubuntu-latest
    needs: test-build-application
    environment: production
    steps:
      - name: Setup ssh
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" > ~/.ssh/known_hosts
      - name: ssh into server
        run:  | # ssh into the server and execute build scripts
          ssh -o ServerAliveInterval=600 -t ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "./buildPortfolio.sh" 
